name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: yarn
    - name: Run test
      run: CI=true yarn test
    - name: Run build
      run: yarn build
